export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const SHCEDULE_TABLE_LOADING = 'SCHEDULE_TABLE_LOADING';
export const SCHEDULE_TABLE_SUCCESS = 'SCHEDULE_TABLE_SUCCESS';
export const SCHEDULE_TABLE_FAILURE = 'SCHEDULE_TABLE_FAILURE';

export const DELETE_SCHEDULE_LOADING = "DELETE_SCHEDULE_LOADING";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILURE = "DELETE_SCHEDULE_FAILURE";

export const TIME_TABLE_LOADING = "TIME_TABLE_LOADING";
export const TIME_TABLE_SUCCESS = "TIME_TABLE_SUCCESS";
export const TIME_TABLE_FAILURE = "TIME_TABLE_FAILURE";

export const ADD_SCHEDULE_LOADING = "ADD_SCHEDULE_LAODING";
export const ADD_SCHEDULE_SUCCESS = "ADD_SCHEDULE_SUCCESS";
export const ADD_SCHEDULE_FAILURE = "ADD_SCHEDULE_FAILURE";

export const RECEPTIONIST_APPOINTMENT_LOADING = "RECEPTIONIST_APPOINTMENT_LOADING";
export const RECEPTIONIST_APPOINTMENT_SUCCESS = "RECEPTIONIST_APPOINTMENT_SUCCESS";
export const RECEPTIONIST_APPOINTMENT_FAILURE = "RECEPTIONIST_APPOINTMENT_FAILURE";

export const ACCEPT_RECEPTIONIST_APPOINTMENT_LOADING = "ACCEPT_RECEPTIONIST_APPOINTMENT_LOADING";
export const ACCEPT_RECEPTIONIST_APPOINTMENT_SUCCESS = "ACCEPT_RECEPTIONIST_APPOINTMENT_SUCCESS";
export const ACCEPT_RECEPTIONIST_APPOINTMENT_FAILURE = "ACCEPT_RECEPTIONIST_APPOINTMENT_FAILURE";

export const DOCTORS_APPOINTMENT_LOADING = "DOCTOR_APPOINTMENT_LOADING";
export const DOCTORS_APPOINTMENT_SUCCESS = "DOCTOR_APPOINTMENT_SUCCESS";
export const DOCTORS_APPOINTMENT_FAILURE = "DOCTOR_APPOINTMENT_FAILURE";

export const LOAD_APPNT_DATA_SUCCESS = "LOAD_APPNT_DATA_SUCCESS";
export const LOAD_DOC_DATA_SUCCESS = "LOAD_DOC_DATA_SUCCESS";
export const LOAD_FREE_TIME_DATA = "LOAD_FREE_TIME_DATA";
export const LOAD_ROOM_DATA_SUCCESS = "LOAD_ROOM_DATA_SUCCESS";
export const SCH_SUR_TABLE_LOADING = "SCH_SUR_TABLE_LOADING";

export const WARD_TABLE_LOADING = "WARD_TABLE_LOADING";
export const WARD_TABLE_SUCCESS = "WARD_TABLE_SUCCESS";
export const WARD_TABLE_FAILURE = "WARD_TABLE_FAILURE";
export const WARD_TABLE_LOAD_WARDS = "WARD_TABLE_LOAD_WARDS";
export const WARD_TABLE_SELECT_WARD = "WARD_TABLE_SELECT_WARD";

export const ADMIT_TABLE_LOADING = "ADMIT_TABLE_LOADING";
export const ADMIT_TABLE_FAILURE = "ADMIT_TABLE_FAILURE";
export const LOAD_ADMIT_ROOM_DATA_SUCCESS = "LOAD_ADMIT_ROOM_DATA_SUCCESS";
export const LOAD_PATIENT_DATA_SUCCESS = "LOAD_PATIENT_DATA_SUCCESS";
export const LOAD_ROOM_TYPES_SUCCESS = "LOAD_ROOM_TYPES_SUCCESS";

export const EMP_SHCEDULE_TABLE_LOADING = "EMP_SHCEDULE_TABLE_LOADING";
export const EMP_SCHEDULE_TABLE_SUCCESS = "EMP_SCHEDULE_TABLE_SUCCESS";
export const EMP_SCHEDULE_TABLE_FAILURE = "EMP_SCHEDULE_TABLE_FAILURE";